modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/coredex-source/EclipseUI/issues"

[[mods]]
modId = "eclipsecore"
version = "${version}"
displayName = "EclipseCore"
description = "Core utilities for Eclipse libraries"
logoFile = "assets/eclipsecore/icon.png"
authors = "EclipseUI Team"
displayURL = "https://github.com/coredex-source/EclipseUI"

[[dependencies.eclipsecore]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.eclipsecore]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},${minecraft_version_max})"
ordering = "NONE"
side = "CLIENT"
