modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/coredex-source/EclipseUI/issues"

[[mods]]
modId = "eclipseplatform"
version = "${version}"
displayName = "EclipsePlatform"
description = "Platform abstraction layer for Eclipse libraries"
logoFile = "assets/eclipseplatform/icon.png"
authors = "EclipseUI Team"
displayURL = "https://github.com/coredex-source/EclipseUI"

[[dependencies.eclipseplatform]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.eclipseplatform]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},${minecraft_version_max})"
ordering = "NONE"
side = "CLIENT"

[[dependencies.eclipseplatform]]
modId = "eclipsecore"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
