modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/coredex-source/EclipseUI/issues"

[[mods]]
modId = "eclipseui_testmod"
version = "${version}"
displayName = "EclipseUI TestMod"
description = '''Test mod demonstrating EclipseUI library integration'''
authors = "coredex-source"
logoFile = "assets/eclipseui_testmod/icon.png"

[[dependencies.eclipseui_testmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eclipseui_testmod]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eclipseui_testmod]]
modId = "eclipseui"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
